name: Test

on: [push]

jobs:
  test-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        brew tap vapor/tap
        brew install vapor/tap/vapor
        sh test.sh

  test-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        eval "$(curl -sL https://apt.vapor.sh)"
        sudo apt-get install swift vapor
        swift test
