name: Test

on: [push]

jobs:
  test-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        brew install libressl
        sh test.sh

  test-linux:
    runs-on: ubuntu-latest
    container:
      image: vapor/swift:5.1-bionic
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: swift test --enable-test-discovery
