name: Test

on: [push]

jobs:
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_11.5.app
    - name: Test
      run: sh test.sh

  Beta:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_12_beta.app
    - name: Test
      run: sh test.sh

  Linux:
    runs-on: ubuntu-latest
    container:
      image: vapor/swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: swift test --enable-test-discovery
