name: Test

on: [push]

jobs:
  test-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app
    - name: Test
      run: sh test.sh

  test-linux:
    runs-on: ubuntu-latest
    container:
      image: vapor/swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: swift test --enable-test-discovery
