name: Test

on: [push]

jobs:
  test-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        brew install libressl
        sh test.sh

  test-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        wget -q https://repo.vapor.codes/apt/keyring.gpg -O- | sudo apt-key add -
        echo "deb https://repo.vapor.codes/apt $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/vapor.list
        sudo apt-get update
        sudo apt-get install swift vapor
        swift test
